version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:16.8.7-ce.0
    restart: always
    privileged: false
    ports:
      - '8080:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '/opt/gitlab/data:/var/opt/gitlab'
      - '/opt/gitlab/logs:/var/log/gitlab'
      - '/opt/gitlab/config:/etc/gitlab'
      - '/opt/gitlab/backups:/home/backup/backups'
      
